### ISSUE TITLE
you don't need to import images, because you never read it via graphql

### ISSUE THREAD

**Issue by muescha** [bvlktech/GatsbyFinds#1]
you don't need to import images, because you never read it via graphql:

https://github.com/bvlktech/GatsbyFinds/blob/6e87f1ad2af2b8ba2e0ddd17f983ee50856a59e5/gatsby-config.js#L16-L22

**Comment by bvlktech** [comment]
It can still be there it doesn't matter plus good that it is there because i might use it in a future update
